spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_users?createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
security:
  jwt:
    secret: "XjL9i3dQkH7aS1oBqZ4mT8vWcE2pR6uY"
    expiration-ms: 900000   # 15 minutes