server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_issues?createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: "XjL9i3dQkH7aS1oBqZ4mT8vWcE2pR6uY"

users:
  base-url: http://localhost:8080
books:
  base-url: http://localhost:8081
